[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
turbine3_hw = "DVsH96ZZeoHV52qzwJecV36RX1v2CChS8bSfPqkgxwwu"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
